apiVersion: v1
kind: Service
metadata:
  name: mylogger-service-develop
  namespace:  mylogger-develop
spec:
  selector:
    app: mylogger
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer