name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job1:
    name: Update deploya
    runs-on: ubuntu-latest 
    steps:
      - name: deploy to cluster
        uses: kodermax/kubectl-aws-eks@master
        with:
          args: apply -f deployment.yaml
        
