name: .NET
on:
  push:
    branches: [ main ]



jobs:
  job1:
    name: Develop
    runs-on: ubuntu-latest 
    steps:
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}

      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Build and push Docker images
        id: dockerbuild
        uses: docker/build-push-action@v2.5.0
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/mylogger:${{ steps.buildnumber.outputs.build_number }}

      - uses: actions/checkout@v2
      - name: Jberlinsky AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Change image Docker
        run: sed -i 's/Param01ImageDocker/${{secrets.DOCKERHUB_USERNAME}}\/mylogger:${{ steps.buildnumber.outputs.build_number }}/' ./k8s/develop/deployment-develop.yaml

      - name: Trigger deploy
        uses: Jberlinsky/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f ./k8s/develop/namespace-develop.yaml -f ./k8s/develop/deployment-develop.yaml -f ./k8s/develop/service-develop.yaml
